language: node_js
node_js:
- '12'
env:
  global:
  # REGISTRY_TOKEN(editor=cozy, app=boulanger)
  - secure: lq5B2bK/PyWI/Kzq59Ij6k/UGNzDnBU1yCNaBextSZtZiaRelGaxhDaiN1/HohVPRBAsOdMTaNH69bMSdAUSsZGy5iVa2Cr8Dk0UMInH6JG2TqzFpuoZsSfv09enUIP7Hf7eUC/GfwzQxowCRCksIZOMROFA0ZdZVEvpUaJqXT49i6PBOQhVUhrdwZT0JvtpFbDxfR/kCl+6XDbmbmUXZwr8ZUZoy0K2EwI29c6AMdZxZkyH2P7vy3+Vh/+2Z5wNvxsrLkDm6b07Uu5ajEtxnugjc9bl/W2HiizaFVvsm0/IQsx7+KVZnufx12Nz9fnaVfNg4F4E9cLWYiujht9FZKxuV0YHor2TSNCkXGnLNpols0XgGoOX/3Z+Fhbbp7ff+E0gQ4x2KubWmVTWsLrsI9cb4JwJNixhYmdN8vikfjG6f2EjaGoprvy+/KzWXDTjfntBckrkf3t5uGh5oCdjjUNnQwK7clOQNgIMnn7rvPpFifxp3oK0dXrJ2dgN2Jzr2pP0n9J+pBACsn8czAo2T/Q0UhEHxrYd4Uxt6XvG4fAfBh1QfCXfNBPL3DyQfnN4rdr1oQE3GHAMNR0byZT2f78WcQAlQlka10qqXvnsRlFVG39Y9pc39DfpxJFvfUASOWVxH7zUl/4eT+IG9RiVkLwlGPJG60zFyACqNKGlpC4=
  # MATTERMOST_HOOK_URL
  - secure: eNrAMzGNmcrcp3j7u/RIdzt2KJf1bSYsfPfVPGgwTn+t85C/Q6dXi+gCdC1Jb5b3BwN1oVL1SrmMJcYMJoOlmmcji4JGGdQl5eaMYmsL5RpBIauHkVv3iyQKl8NUHsPp9UfSJtBbwcW7AbkUyM5rYnY0sp5Nx0ADlrtjMHtrzBb82zds+knpeOuIGDGZau9Km99XNW97fKFI+3wHzrQrc6L86gGVAmupQ/55unvbf8WFCSQsnEmur5u+cwdVVZYgHXcfM7QCAZYpO0MJvejzIFOQerIcKu/3pWQdIiQIuoqN08qfb2PiZtvivALvDCYhcrPoABr/mvwu9VAPQJbrBWwOUT8da1T7uPoNnhZAmLloE0opkwPF79WMiY6wPy4trKqVdfVXkkoDmamIyKFPK2+IRWUE6VKRrAklqJcO9rmIKGJVUD+Dd/11PzN+ECQ0fB3vXEn4EjOmsnZRB5kx1W3lWbjNIv9ERApx1SamjMHNyt8tPMs/hthbeBhBr+AnnWYzH6f4wjuTQOPN3Y+KOca2GBALiExEAAftSRl1IQuvZ6e9rvnVcX2i332lDakIIRZ2H81V3S7h+esFOOrCcBLC89WSENHprBqLRQrskEOETABFpobNfIWt6AaU66N1OJOqZGclzxW3jmOX8Tp2XdIWWrtTV1MKRVo3hPFcVvg=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_7b91a7b81823_key -iv $encrypted_7b91a7b81823_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
