language: node_js
node_js:
  - '8'
env:
  global:
    # cozy-bot GITHUB_TOKEN
    - secure: "HpQcblizdzKQ4M1eg6IYLenw6hHNXSdsI7AIdKPQR+aYm0aSt9E9tZbUpu5xBCBiw5M5U4ea+zrgmM8ZNzzybSqQi1n07N+lH9+xROhiYCE6lRuqrsozQKe5Oi7Xet4TrsUdOs1CC0ueOieRdb4h4AXiBpomLBpTyfK1EwtXHhtJo0OfA6vpUEfT4baRd5ys8KGcwwAk5UrBbPGRXScsCCZSWhPLSw2oWqdIlUdtayAelJkdJVFJPjjqpm6vByhn04POxL5AsgRmm1YJLtbT+QvuTW/rWNg5/YHb2qzjVdQyJzxbbP/obZ/KnhcP/mJ/jXqwU7NIrS+zcb935D4SZ9QJw7AzromjPUL6RkhAw4MQZg3YgswEfZcojWgVt6ueKGpSk5OccL8wwePaoil2n2pgmktgrLQu23BUiIRCvazkcLDxVG1DKcKk1D3M5UNTxJ8IQ4LzKIJvMvjynfa9wq7KVL6JtgVlMuZah07LtTaWVK7tw4dH2OA5rYmGQ66eXXES29UAH8oJTwYHVQefJe/ru5AdZcjCvZuA6jS5sUBZYqhjq8P8osr3RmfhE4IFEJo4/n9dm9CzvGnYggGJpMDbkcpHhwQQcp3NWuwoxehQy6YQB3s5oS4+QhJTpn4kgx3l0ozjrNrtPp/Y+yWldJ9Rb83gbEwT7dInIU4m6K0="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
deploy:
  - provider: script
    repo: konnectors/boulanger
    skip-cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-boulanger
    skip-cleanup: true
    script: DEPLOY_BRANCH=latest yarn deploy
    on:
      branch: prod
